[package]
name = "gb_emulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.6.0"
chrono = "0.4.41"
lazy_static = "1.5.0"
sdl2 = "0.37.0"

[dev-dependencies]
rand = "0.8.5"
